### ISSUE TITLE
Build out PF Seed app on top of OpenShift

### ISSUE THREAD

**Issue by evwilkin** [rh-uxd/uxd-infrastructure#5]

**Comment by redallen** [comment]
This one was super easy.

1. `oc new-project patternfly-seed-app`
2. `oc new-app openshift/nodejs:12~https://github.com/patternfly/patternfly-react-seed.git --name=patternfly-seed-app`
3. `oc expose svc/patternfly-seed-app`
4. Wait ~10m
5. http://patternfly-seed-app-patternfly-seed-app.apps.ocp4.patternfly.org/ works!
