### ISSUE TITLE
Deploy RHMI on top of OpenShift cluster & handoff

### ISSUE THREAD

**Issue by evwilkin** [rh-uxd/uxd-infrastructure#8]

**Comment by ddonahue007** [comment]
Steps taken to deploy RHMI on openstack/openshift cluster

Prerequisites:
- Must have resources available to build an openshift cluster
    3 masters - (RAM 16384gb,  DISK 40gb, CPUs 4 )
    2 workers - (RAM 16384gb, DISK  40gb, CPUs  8)

1. Build Openshift cluster using the create-cluster.sh script.([HERE](https://github.com/rh-uxd/uxd-infrastructure))
`> ./create-cluster.sh -c "rhmi" -w ci.m1.xlarge -x 2`

2. Follow these instructions
https://docs.google.com/document/d/1klpSUBKkg-1OdEY5UEhF1CHfdftaPuQ_2wAh2OagikE/edit

**Comment by ddonahue007** [comment]
Changes needed:

Step 11: (Failed)
`> USE_CLUSTER_STORAGE=true operator-sdk run --local --namespace=redhat-rhmi-operator`
[Deprecation Notice] Operator SDK has a new CLI and project layout that is aligned with Kubebuilder.
See `operator-sdk init -h` and the following doc on how to scaffold a new project:
https://sdk.operatorframework.io/docs/golang/quickstart/
To migrate existing projects to the new layout see:
https://sdk.operatorframework.io/docs/golang/migration/project_migration_guide/
 
Flag --local has been deprecated, use 'run local' instead
Flag --namespace has been deprecated, use --watch-namespaces (with --local) or --operator-namespace (with --olm) instead
INFO[0000] --namespace is deprecated; use --watch-namespace instead. 

Used the following command instead:
`> USE_CLUSTER_STORAGE=true operator-sdk run local --watch-namespace=redhat-rhmi-operator`

**Comment by ddonahue007** [comment]
Handed cluster of to Mark F.
